config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  devise_for :users
  resources :watchlists do
    resources :items
  end

  root to: "watchlists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :watchlist
  validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  has_many :watchlists, dependent: :destroy
  validates_presence_of :email, :password

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :users, optional: true
  validates_presence_of :list_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_watchlist

  def create
    @item = @watchlist.items.create(item_params)
    redirect_to @watchlist
  end

  def destroy
    @item = @watchlist.items.find(params[:id])
    @item.destroy
    redirect_to @watchlist
  end

  private

  def set_watchlist
    @watchlist = current_user.watchlists.find(params[:watchlist_id])
  end

  def item_params
    params[:item].permit(:title, :year, :genre)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
    @current_user = current_user.id
  end
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
  before_action :set_watchlist, only: %i[show edit update destroy]

  # GET /watchlists or /watchlists.json
  def index
    @watchlists = current_user.watchlists.all
  end

  # GET /watchlists/1 or /watchlists/1.json
  def show
  end

  # GET /watchlists/new
  def new
    @watchlist = current_user.watchlists.new
  end

  # GET /watchlists/1/edit
  def edit
  end

  # POST /watchlists or /watchlists.json
  def create
    @watchlist = current_user.watchlists.new(watchlist_params)

    respond_to do |format|
      if @watchlist.save
        format.html { redirect_to watchlist_url(@watchlist), notice: "Watchlist was successfully created." }
        format.json { render :show, status: :created, location: @watchlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @watchlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watchlists/1 or /watchlists/1.json
  def update
    respond_to do |format|
      if @watchlist.update(watchlist_params)
        format.html { redirect_to watchlist_url(@watchlist), notice: "Watchlist was successfully updated." }
        format.json { render :show, status: :ok, location: @watchlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @watchlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watchlists/1 or /watchlists/1.json
  def destroy
    @watchlist.destroy

    respond_to do |format|
      format.html { redirect_to watchlists_url, notice: "Watchlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_watchlist
    @watchlist = current_user.watchlists.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def watchlist_params
    params.require(:watchlist).permit(:list_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/items/_form.html.erb
<%= form_for([@watchlist, @watchlist.items.build]) do |form| %>
  <% if @watchlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(watchlist.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% watchlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>Add New Entry</div>

  <div class="field">
    <%= form.text_field :title, placeholder: "Title" %>
    <%= form.text_field :year, placeholder: "Year" %>
    <%= form.text_field :genre, placeholder: "Genre" %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<p>
  <%= item.title %> (<%= item.year %>) - <%= item.genre %> 
  <%= link_to "Delete", watchlist_item_path(@watchlist, item.id), method: :delete, data: { confirm: "Are you sure?" } %>
</p>

app/views/items/new.html.erb
<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %> 

    <nav id="nav_bar">
      <div>
        <a href="/watchlists">Home</a>
      </div>
      <div>
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> | 
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/watchlists/_form.html.erb
<%= form_with(model: watchlist) do |form| %>
  <% if @watchlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(watchlist.errors.count, "error") %> prohibited this watchlist from being saved:</h2>

      <ul>
        <% watchlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :list_name %>
    <%= form.text_field :list_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/watchlists/edit.html.erb
<h1>Edit Watchlist</h1>

<%= render 'form', watchlist: @watchlist %>

<%= link_to 'Show', @watchlist %> |
<%= link_to 'Back', watchlists_path %>

app/views/watchlists/index.html.erb
<h1 id="site_title">Movie Tracker</h1>

<div id="table_cont">
  <table>
    <thead>
      <tr>
        <th>Watchlists</th>
        <th colspan="3"></th>
      </tr>
    </thead>
      <tbody>
        <% @watchlists.each do |watchlist| %>
          <tr>
            <td id="table_list_name"><%= watchlist.list_name %></td>
            <td><%= link_to 'Show', watchlist %></td>
            <td><%= link_to 'Edit', edit_watchlist_path(watchlist) %></td>
            <td><%= link_to 'Destroy', watchlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

<br>

<%= link_to 'Create New Watchlist', new_watchlist_path %>

app/views/watchlists/new.html.erb
<h1>Create New Watchlist</h1>

<%= render 'form', watchlist: @watchlist %>

<%= link_to 'Back', watchlists_path %>

app/views/watchlists/show.html.erb
<h2 id="list_name"><%= @watchlist.list_name %></h2>

<div id="items_wrapper">
  <%= render @watchlist.items %>
</div>

<div id="form">
    <%= render "items/form" %>
</div>

<%= link_to 'Edit List Name', edit_watchlist_path(@watchlist) %> |
<%= link_to 'Back', watchlists_path %>